<!--
 * @Descripttion: 
 * @version: 
 * @Author: CC
 * @Date: 2022-03-09 08:56:48
 * @LastEditors: sueRimn
 * @LastEditTime: 2022-03-14 17:16:36
-->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script>
    function fn(nums) {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          reject(nums * 2)
        }, 1000)
      })
    }
    async function test() {
      let res1 = await fn(1)
      let res2 = await fn(res1)
      let res3 = await fn(res2)
      console.log('res3', res3);
    }
    test()    //效果 3秒后输出 8


    // 借助 promise 和 generator 实现

    function* gen() {
      const num1 = yield fn(1)
      const num2 = yield fn(num1)
      const num3 = yield fn(num2)
      return num3
    }
    // 实现版本
    function generatorToAsync(generatorFn) {
      // return function () {
      return new Promise((resolve, reject) => {
        const gen = generatorFn()
        const next1 = gen.next()
        console.log('next1', next1);
        next1.value.then(res => {
          const next2 = gen.next(res)
          next2.value.then(res => {
            const next3 = gen.next(res)
            next3.value.then(res => {
              resolve(res)
            })
          })
        })
      })
      // }
    }
    // generatorToAsync(gen).then(res => {
    //   console.log('res', res);
    // })
    // result()

    // 优化版本  
    function generatorToAsync2(generatorFn) {
      return function () {
        return new Promise((resolve, reject) => {
          const gen = generatorFn()
          function fn(key, args) {
            try {
              reslut = gen[key](args) // 这里有可能会执行返回reject状态的Promise
            } catch (error) {
              console.log('v', error);
              return reject(error) // 报错的话会走catch，直接reject
            }
            let { done, value } = reslut
            // console.log('value', value);
            if (!done) {
              // value有可能是：常量，Promise，Promise有可能是成功或者失败
              return Promise.resolve(value).then(val => fn('next', val), err => {
                fn('throw', err)
              })
            } else {
              resolve(value)
            }
          }
          fn('next')
        })
      }
    }

    generatorToAsync2(gen)().then(res => {
      console.log('5555');
      console.log('res', res);
    }, rej => {
      console.log('rej', rej);
    })





  </script>
</body>

</html>